### ISSUE TITLE
An attempt to answer the README's question

### ISSUE THREAD

**Issue by ctrlcctrlv** [rsheeter/google_fonts_sources#1]
> What if you wanted ALL the sources - not the binaries - for Google Fonts?

Well, you'd need the source for Glyphs.app in most cases.

And since that proprietary program only works on macOS, you'd need the source to that too.

:rofl: 

No, no, to be serious, good project, but Google has never cared about source-availability or free toolchain builds, and it's led to a lot of issues.

**Comment by rsheeter** [comment]
> Google has never cared about source-availability or free toolchain builds

I think I might respectfully beg to differ. Google funds open tools to manipulate and build fonts and provides font source whenever possible. Hopefully the ecosystem, while imperfect, is better off than it would be were that not the case.
